apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mpa-frontend
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: web
    app: web
  type: NodePort